services:
  - type: web
    name: devpulse
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install && npx prisma generate && npx prisma db push --accept-data-loss && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        sync: false
      - key: DATABASE_URL
        value: file:./dev.db
      - key: GEMINI_API_KEY
        sync: false
